### PR TITLE
Fix compilation errors and gitignores

### PR DESCRIPTION
**Pull request by msedwar**
This change fixes compilation errors present when performing a full project build using `make`.

This change also ensures that after a build (with no change to commitable generated files), the tree will continue to be clean.

### CODE REVIEW

**Comment by larryliu0820** [comment]
Should we change all the imports once we rename `tensor.h`? Like the one in `Evalue.h`. Speaking of which, should we rename `Evalue.h` to `EValue.h` to match the struct name?

**Comment by msedwar** [comment]
> Should we change all the imports once we rename `tensor.h`?

As far as I can tell, all of the includes in /core use the capitalized version of `Tensor.h` (so I renamed it to match how it was included in source).

> Like the one in `Evalue.h`. Speaking of which, should we rename `Evalue.h` to `EValue.h` to match the struct name?

Good point, I think that would be a good idea. @JacobSzwejbka do you have thoughts?

**Comment by larryliu0820** [comment]
> As far as I can tell, all of the includes in /core use the capitalized version of `Tensor.h` (so I renamed it to match how it was included in source).

I see it's been changing back and forth. PR looks good to me.

**Comment by JacobSzwejbka** [comment]
> > As far as I can tell, all of the includes in /core use the capitalized version of `Tensor.h` (so I renamed it to match how it was included in source).
> 
> I see it's been changing back and forth. PR looks good to me.

I wasn't sure which to go with. I was trying to make it similar to current torch, but there it also seems inconsistent. #include <ATen/Tensor.h> vs <caffe2/core/tensor.h>. Similarly Evalue.h could be EValue.h to match the struct or evalue.h to match the lower case of <ATen/core/ivalue.h>

**Comment by msedwar** [comment]
Pull main and fix conflicts before merge.

**Comment by iseeyuan** [comment]
> 

@JacobSzwejbka No preference for me at this time. We could comeback and revisit this.

**Pull request merged**
